# Generated by Django 6.1.1 on 2026-09-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costomers',
            new_name='Customers',
        ),
    ]
