# Generated by Django 6.1.1 on 2026-09-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_rename_costomers_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
