# Generated by Django 6.1.1 on 2026-09-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_customers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('famale', 'Famale')], default='male', max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'father_name')},
            },
        ),
    ]
